### ISSUE TITLE
Add persistence to conversations

### ISSUE THREAD

**Issue by mpp112358** [mpp112358/askai#2]
Currently, when you run askai you start a conversation that will keep running until you close Emacs. It would be desirable to be able to save conversations to disk, and to retrieve them later from disk to continue using that conversation as context for the chat.

**Comment by mpp112358** [comment]
# TODO
 
- [x] Decide on a format for the conversations file.
- [x] Decide on a default location for the conversations file.
- [ ] Create a customizable variable for the location of the conversations file.
- [x] Define a function to save a conversation.
- [x] Define a function to show a list of available conversations.
- [x] Define a function to load a conversation.
- [ ] Define the overall workflow (start a new conversation by default, show the available conversations by default...).
- [ ] Define a function to delete conversations.
- [x] Get a three-word summary from the AI itself.
